// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../Numeric_Operations.fs"
      "../Tuple_Operations.fs"
      "../ListEager.fs"
      "../ListOfList.fs"
      "../Predicates.fs"
      "../Types.fs"
      "../List_Operations.fs"
      "../List_Lazy_Operations.fs"
      "../List_Iterators.fs"
      "../ListRefs.fs"
      "../Stack.fs"
      "../StackRefs.fs"
      "../Tree.fs"
      "../Test_Stack_Types_Native.fs"
      "../Test_StackWithRefs.fs"
      "../Test_StackWithTypes.fs"
      "../Test_Tree_Operations.fs"
      "../Currying.fs"
      "../UnCurrying.fs"
      "../Test_LazyLists.fs"
      "../ConsultationsQuestions.fs"
      "../Test_RefToLists.fs"
      "../Test_ListE.fs"
      "../Test_Lab1_eList.fs"
      "../Test_Lab2_eList.fs"
      "../Test_Lab7_eList.fs"
