// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references.fsx"
#load "../ListOfList.fs"
      "../Types.fs"
      "../Predicates.fs"
      "../List_Operations.fs"
      "../List_Iterators.fs"
      "../ListRefs.fs"
      "../Stack.fs"
      "../StackRefs.fs"
      "../Tree.fs"
      "../Test_Stack_Types_Native.fs"
      "../Test_RefToLists.fs"
      "../Test_StackWithRefs.fs"
      "../Test_StackWithTypes.fs"
      "../Test_Tree_Operations.fs"
      "../Currying.fs"
      "../UnCurrying.fs"
